# Generated by Django 6.0.1 on 2026-02-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("EXPIRED", "Expired"),
                ],
                max_length=7,
            ),
        ),
    ]
